baseURL = "https://hrishikeshsnamputiri.github.io"
title = "thirumeni"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Hrishikesh S Namputiri"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Hrishikesh's personal portfolio"
keywords = "CP,personal"
info = ["Future ICPC World Finalist","I use Arch btw", "Emacs User"]
avatarURL = "https://w7.pngwing.com/pngs/478/231/png-transparent-computer-icons-astronaut-outer-space-astronaut-outer-space-astronaut-computer-icons.png"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/HrishikeshSNamputiri/amfoss-tasks/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# Menu links
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "ICPC Training Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"
[[menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/HrishikeshSNamputiri"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
